spring:
  application:
    name: parametre
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: false
  data:
    redis:
      host: localhost
      port: 16379
      password: redispass